# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  prometheus:
    config:
      scrape_configs:
        - job_name: host-app
          scrape_interval: 5s
          metrics_path: /metrics
          static_configs:
            - targets: ["host.docker.internal:9321"]

exporters:
  debug:

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, spanmetrics, otlp]
    metrics:
      receivers: [otlp, spanmetrics, prometheus]
      processors: [filter, batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
